name: Some Workflow

on:
  schedule:
    - cron:  '0 4 3 * *'
  workflow_dispatch:
    inputs:
      an_input:
        description: 'Input?'
        required: true
        default: 'Foo'
jobs:
  build:
  # Do something with ${{ github.event.inputs.an_input }}
  echo ${IN}
  env:
    IN: ${{ github.event.inputs.an_input }}
