name: Some Workflow

on:
  schedule:
    - cron:  '0 4 3 * *'
  workflow_dispatch:
    inputs:
      an_input:
        type: boolean
        required: true
        default: true
jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      -name: Print some text
       run: echo ${IN}
    env:
        IN: ${{ github.event.inputs.an_input }}
