name: Some Workflow

on:
  schedule:
    - cron:  "5 2 14 7 *"
    - cron:  "15 2 14 7 *"
      inputs:
        an_input:
          type: boolean
          required: true
          default: true
    - cron:  "10 2 14 7 *"
    - cron:  "20 2 14 7 *"
      inputs:
        an_input:
          type: boolean
          required: true
          default: false
  workflow_dispatch:
    inputs:
      an_input:
        type: boolean
        required: true
        default: true
jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Print some text
        run: echo ${IN}
        env:
          IN: ${{ github.event.inputs.an_input }}
