name: Some Workflow

inputs:
  an_input:
    type: boolean
    required: true
    default: false
on:
  schedule:
    - cron:  "5 8 14 7 *"
    - cron:  "15 8 14 7 *"
  workflow_dispatch:
    inputs:
      an_input:
        type: boolean
        required: true
        default: true
jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Print some text
        run: echo ${IN}
        env:
          IN: ${{ github.event.inputs.an_input }}
